version: "3.0"
name: olympsis-dev

volumes:
    mongo-data:
    redis-data:

secrets:
    key-file:
        file: ./files/localhost.key
    cert-file:
        file: ./files/localhost.crt
    apns-key:
        file: ./files/AuthKey_5PR7XV2XXL.p8
    firebase-token:
        file: ./files/firebase-credentials.json
    apple_key_id:
        environment: APPLE_KEY_ID
    apple_team_id:
        environment: APPLE_TEAM_ID
    mapkit_token:
        environment: MAPKIT_TOKEN
    stripe_token:
        environment: STRIPE_TOKEN

services:
    gateway:
        container_name: gateway
        image: apache/apisix
        restart: always
        volumes:
            - ./files/apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
            - ./files/apisix-routes.yaml:/usr/local/apisix/conf/apisix.yaml:ro
        ports:
            - 9080:9080
    server:
        build:
            context: .
            no_cache: true
        container_name: server
        restart: always
        ports:
            - 80:80
        volumes:
            - ./files/firebase-credentials.json:/app/firebase-credentials.json:ro
            - ./files/localhost.key:/app/localhost.key:ro
            - ./files/localhost.crt:/app/localhost.crt:ro
            - ./files/AuthKey_5PR7XV2XXL.p8:/app/AuthKey_5PR7XV2XXL.p8:ro
            - ./files/AuthKey_FQ38XX3HXG.p8:/app/AuthKey_FQ38XX3HXG.p8:ro
        env_file: .env.dev
        depends_on:
            - gateway
            - mongo
            - redis

    storage:
        image: us-central1-docker.pkg.dev/olympsis-485522/storage/dev:v0.3.1
        container_name: storage
        restart: always
        ports:
            - 8081:80
        volumes:
            - ./files/firebase-credentials.json:/app/firebase-credentials.json:ro
            - ./files/storage-credentials.json:/app/storage-credentials.json:ro
        env_file: .env.dev
        depends_on:
            - gateway

    # client-web:
    #     container_name: client-web
    #     image: us-central1-docker.pkg.dev/olympsis-485522/client-web/dev:v0.2.0
    #     restart: always
    #     ports:
    #         - 3000:80
    #     depends_on:
    #         - gateway

    # chat:
    #     container_name: chat
    #     restart: always
    #     ports:
    #         - 8082:80
    #     depends_on:
    #         - redis

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: olympsis
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db

    redis:
        container_name: redis
        image: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data