version: "3.0"

volumes:
    mongo-data:
        external: true
    redis-data:
        external: true

services:
    gateway:
        container_name: gateway
        image: apache/apisix
        restart: always
        volumes:
            - ./apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
            - ./apisix-routes.yaml:/usr/local/apisix/conf/apisix.yaml:ro
        networks:
            - olympsis
        ports:
            - 9080:9080
            
    server:
        container_name: server
        image: us-central1-docker.pkg.dev/olympsis-485522/server/release:v0.8.1
        restart: always
        pull_policy: always
        ports:
            - 8080:80
        networks:
            - olympsis
        volumes:
            - ./AuthKey_PWK5QB5Z6R.p8:/app/AuthKey_PWK5QB5Z6R.p8:ro
            - ./firebase-credentials.json:/app/firebase-credentials.json:ro
        env_file: .env.prod

    storage:
        container_name: storage
        image: us-central1-docker.pkg.dev/olympsis-485522/storage/release:v0.3.0
        restart: always
        pull_policy: always
        ports:
            - 8081:80
        networks:
            - olympsis
        volumes:
            - ./firebase-credentials.json:/app/firebase-credentials.json:ro
            - ./storage-credentials.json:/app/storage-credentials.json:ro
        env_file: .env.prod

    # chat:
    #     container_name: chat
    #     image: us-central1-docker.pkg.dev/olympsis-408521/main/chat:v1.0.0
    #     restart: always
    #     pull_policy: always
    #     ports:
    #         - 8082:7003

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        networks:
            - olympsis
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: olympsis
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db

    redis:
        container_name: redis
        image: redis
        restart: always
        networks:
            - olympsis
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data

networks:
    olympsis:
        driver: bridge