version: "3.0"
name: olympsis-dev

volumes:
    db-data:
    redis-data:

secrets:
    key-file:
        file: ./files/localhost.key
    cert-file:
        file: ./files/localhost.crt
    apns-key:
        file: ./files/AuthKey_5MP3VW78BZ.p8
    firebase-token:
        file: ./files/firebase-credentials.json
    apple_key_id:
        environment: APPLE_KEY_ID
    apple_team_id:
        environment: APPLE_TEAM_ID
    mapkit_token:
        environment: MAPKIT_TOKEN
    stripe_token:
        environment: STRIPE_TOKEN

services:
    server:
        build: .
        container_name: server
        restart: always
        ports:
            - 80:80
        volumes:
            - ./files/firebase-credentials.json:/app/firebase-credentials.json:ro
            - ./files/localhost.key:/app/localhost.key:ro
            - ./files/localhost.crt:/app/localhost.crt:ro
            - ./files/AuthKey_5MP3VW78BZ.p8:/app/AuthKey_5MP3VW78BZ.p8:ro
        environment:
            PORT: 80
            HTTP: UNSECURE
            MODE: DEVELOPMENT
            KEY_FILE_PATH: ./files/localhost.key
            CERT_FILE_PATH: ./files/localhost.crt
            MONGO_ADDRESS: mongo
            MONGO_USERNAME: admin
            MONGO_PASSWORD: olympsis
            REDIS_ADDRESS: redis:6379
            APNS_FILE_PATH: ./AuthKey_5MP3VW78BZ.p8
            STORAGE_URL: http://storage:8081
            FIREBASE_FILE_PATH: ./firebase-credentials.json
            STRIPE_TOKEN: sk_test_51P33HvRxf68pt9NZisRo9RRtCn4OJwspd4juCFnJEip0e7oSx0WPm7Cb2M7WJ7VRs7i5LZDSs9fuyV6QahQgPuaI00oYr8nc89
            MAPKIT_TOKEN: eyJraWQiOiI3NjZXUjMyNVM4IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiI1QTZINDlRODVEIiwiaWF0IjoxNzQwMjg0NjQ1LCJleHAiOjE3NDA5MDIzOTl9.LPQlwicCot1AmWF8utQclYB2XCoN5C4oeOQyDmo-SlAGP_zWVpExAbcQGyEl6NvnWtLIM1cVLpGLcln9DxrZNw
            APPLE_KEY_ID: 5MP3VW78BZ
            APPLE_TEAM_ID: 5A6H49Q85D
        depends_on:
            - mongo
            - redis

    # storage:
    #     container_name: storage
    #     restart: always
    #     ports:
    #         - 8081:80
    #     depends_on:
    #         - master

    # chat:
    #     container_name: chat
    #     restart: always
    #     ports:
    #         - 8082:80
    #     depends_on:
    #         - redis

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: olympsis
        ports:
            - 27017:27017
        volumes:
            - db-data:/data/db
            # - ./master-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    redis:
        container_name: redis
        image: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data