FROM golang:1.22-bullseye
WORKDIR /app

COPY ./ ./
COPY /tools/localhost.crt /app/localhost.crt
COPY /tools/localhost.key /app/localhost.key

# RUN --mount=type=secret,id=crt,target=/root/app/localhost.key \
#     --mount=type=secret,id=key,target=/root/app/localhost.key \
#     go build -o /docker

RUN go build -o /docker
RUN go mod download

ENV PORT=443
ENV MODE=DEVELOPMENT

ENV DB_USR=server
ENV DB_PASS=RvmeTaUvkGs7Vc8e
ENV DB_NAME=olympsis
ENV DB_ADDR=production.md0v8.mongodb.net

ENV AUTH_COL=auth
ENV USER_COL=users
ENV CLUB_COL=clubs
ENV ORG_COL=organizations
ENV EVENT_COL=events
ENV FIELD_COL=fields
ENV POST_COL=posts
ENV CLUB_INVITE_COL=clubInvites
ENV COMMENTS_COL=comments
ENV FRIEND_REQUEST_COL=friendRequests
ENV CLUB_APPLICATIONS_COL=clubApplications
ENV ORG_APPLICATIONS_COL=organizationApplications

ENV EVENT_INVITATIONS_COL=eventInvitations
ENV CLUB_INVITATIONS_COL=clubInvitations
ENV ORG_INVITATIONS_COL=organizationInvitations

ENV BUG_REPORT_COL=bugReports
ENV POST_REPORT_COL=postReports
ENV FIELD_REPORT_COL=fieldReports
ENV EVENT_REPORT_COL=eventReports
ENV MEMBER_REPORT_COL=memberReports

ENV NOTIFY=true
ENV NOTIF_URL=https://notifications-p3dy744wqq-uc.a.run.app

EXPOSE 443

CMD ["/docker"]