FROM golang:1.24-alpine
WORKDIR /app
COPY ./ ./
RUN go build -o /docker
RUN go mod download

ENV PORT=80
ENV MODE=PRODUCTION

ENV DB_USER=server
ENV DB_PASS=RvmeTaUvkGs7Vc8e
ENV DB_NAME=olympsis
ENV DB_ADDR=production.md0v8.mongodb.net

ENV ANNOUNCEMENT_COLLECTION=announcements

ENV AUTHENTICATION_COLLECTION=auth
ENV USER_COLLECTION=users
ENV FRIEND_REQUEST_COLLECTION=friendRequests

ENV POSTS_COLLECTION=posts
ENV POST_COMMENTS_COLLECTION=postComments
ENV POST_REACTIONS_COLLECTION=postReactions

ENV CLUB_COLLECTION=clubs
ENV CLUB_INVITE_COLLECTION=clubInvites
ENV CLUB_MEMBERS_COLLECTION=clubMembers
ENV CLUB_INVITATION_COLLECTION=clubInvitations
ENV CLUB_APPLICATION_COLLECTION=clubApplications

ENV ORGANIZATION_COLLECTION=organizations
ENV ORGANIZATION_INVITATION_COLLECTION=organizationInvitations
ENV ORGANIZATION_APPLICATION_COLLECTION=organizationApplications
ENV ORGANIZATION_MEMBERS_COLLECTION=organizationMembers

ENV VENUES_COLLECTION=venues

ENV EVENTS_COLLECTION=events
ENV EVENT_LOGS_COLLECTION=eventLogs
ENV EVENT_VIEWS_COLLECTION=eventViews
ENV EVENT_TEAMS_COLLECTION=eventTeams
ENV EVENT_COMMENTS_COLLECTION=eventComments
ENV EVENT_INVITATIONS_COLLECTION=eventInvitations
ENV EVENT_PARTICIPANTS_COLLECTION=eventParticipants

ENV CLUB_TRANSACTIONS_COLLECTION=clubTransactions
ENV CLUB_FINANCIAL_ACCOUNTS_COLLECTION=clubFinancialAccounts

ENV EVENT_INVITATION_COLLECTION=eventInvitations
ENV CLUB_INVITATION_COLLECTION=clubInvitations
ENV ORG_INVITATION_COLLECTION=organizationInvitations

ENV BUG_REPORT_COLLECTION=bugReports
ENV POST_REPORT_COLLECTION=postReports
ENV VENUE_REPORT_COLLECTION=venueReports
ENV EVENT_REPORT_COLLECTION=eventReports
ENV MEMBER_REPORT_COLLECTION=memberReports

ENV LOCALE_DB=locales
ENV COUNTRY_COLLECTION=countries
ENV ADMIN_AREA_COLLECTION=administrativeAreas
ENV SUB_ADMIN_AREA_COLLECTION=subAdministrativeAreas

ENV TAGS_COLLECTION=tags
ENV SPORTS_COLLECTION=sports

ENV NOTIFY=true
ENV NOTIF_URL=http://notif:8083

ENV STORAGE_URL=http://storage:8081

ENV FIREBASE_FILE_PATH=/files/firebase-credentials.json

EXPOSE 80

CMD ["/docker"]