FROM golang:1.20-bullseye
WORKDIR /app
COPY ./ ./
RUN go build -o /docker
RUN go mod download
ENV PORT=8080

ENV KEYID=JN25FUC9X2
ENV TEAMID=5A6H49Q85D

ENV DB_ADDR=192.168.1.205
ENV DB_USR=service
ENV DB_PASS=qN1PHHgo6L942AvpTgGQ
ENV DB_NAME=olympsis

ENV STORAGE_ADDR=192.168.1.205:9000
ENV STORAGE_ACCESS_KEY=p4eHM3a4v3wGB2ro
ENV STORAGE_SECRET_KEY=WbPjehYtD3wO4V4PNlYwJwWiPRy6qqqN

ENV AUTH_COL=auth
ENV USER_COL=users
ENV CLUB_COL=clubs
ENV ORG_COL=organizations
ENV EVENT_COL=events
ENV FIELD_COL=fields
ENV POST_COL=posts
ENV CINVITE_COL=clubInvites
ENV COMMENTS_COL=comments
ENV FREQUEST_COL=friendRequests
ENV CAPPICATIONS_COL=clubApplications
ENV OAPPICATIONS_COL=organizationApplications

ENV KEY=SZkp78avQkxGyjRakxb5Ob08zqjguNRA


ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=20031998
ENV TOPIC_DB_NAME=olympsis_notif

EXPOSE 8080

CMD ["/docker"]