version: "3"

services:

  # Master server
  master:
    container_name: master
    image: olympsis/server:latest
    restart: always
    ports:
      - "8080:8080/tcp"
    depends_on:
      - apisix
      - dashboard
      - etcd
    networks:
      - olympsis

  # Chat server
  chat:
    container_name: chat
    image: olympsis/chat:latest
    restart: always
    ports:
      - "8081:8081/tcp"
    networks:
      - olympsis

  # Storage processing server
  storage:
    container_name: storage
    image: olympsis/storage:latest
    restart: always
    ports:
      - "8082:8082/tcp"
    networks:
      - olympsis
  
  database:
    container_name: database
    image: mongo:latest
    restart: always
    networks:
      - olympsis