// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: grpcapi/invite.proto

package invitepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mirrors models.InviteType. UNSPECIFIED is the proto3 zero value.
type InviteType int32

const (
	InviteType_INVITE_TYPE_UNSPECIFIED InviteType = 0
	InviteType_EVENT                   InviteType = 1
	InviteType_TEAM                    InviteType = 2
	InviteType_CLUB                    InviteType = 3
	InviteType_ORG                     InviteType = 4
)

// Enum value maps for InviteType.
var (
	InviteType_name = map[int32]string{
		0: "INVITE_TYPE_UNSPECIFIED",
		1: "EVENT",
		2: "TEAM",
		3: "CLUB",
		4: "ORG",
	}
	InviteType_value = map[string]int32{
		"INVITE_TYPE_UNSPECIFIED": 0,
		"EVENT":                   1,
		"TEAM":                    2,
		"CLUB":                    3,
		"ORG":                     4,
	}
)

func (x InviteType) Enum() *InviteType {
	p := new(InviteType)
	*p = x
	return p
}

func (x InviteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcapi_invite_proto_enumTypes[0].Descriptor()
}

func (InviteType) Type() protoreflect.EnumType {
	return &file_grpcapi_invite_proto_enumTypes[0]
}

func (x InviteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteType.Descriptor instead.
func (InviteType) EnumDescriptor() ([]byte, []int) {
	return file_grpcapi_invite_proto_rawDescGZIP(), []int{0}
}

// Mirrors models.InviteStatus. UNSPECIFIED doubles as "no filter" on requests.
type InviteStatus int32

const (
	InviteStatus_INVITE_STATUS_UNSPECIFIED InviteStatus = 0
	InviteStatus_PENDING                   InviteStatus = 1
	InviteStatus_ACCEPTED                  InviteStatus = 2
	InviteStatus_DECLINED                  InviteStatus = 3
)

// Enum value maps for InviteStatus.
var (
	InviteStatus_name = map[int32]string{
		0: "INVITE_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "ACCEPTED",
		3: "DECLINED",
	}
	InviteStatus_value = map[string]int32{
		"INVITE_STATUS_UNSPECIFIED": 0,
		"PENDING":                   1,
		"ACCEPTED":                  2,
		"DECLINED":                  3,
	}
)

func (x InviteStatus) Enum() *InviteStatus {
	p := new(InviteStatus)
	*p = x
	return p
}

func (x InviteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcapi_invite_proto_enumTypes[1].Descriptor()
}

func (InviteStatus) Type() protoreflect.EnumType {
	return &file_grpcapi_invite_proto_enumTypes[1]
}

func (x InviteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteStatus.Descriptor instead.
func (InviteStatus) EnumDescriptor() ([]byte, []int) {
	return file_grpcapi_invite_proto_rawDescGZIP(), []int{1}
}

// Invite is the wire form of models.InviteRequest: the id is a hex string and
// timestamps are unix milliseconds (what bson.DateTime stores natively).
type Invite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          InviteType             `protobuf:"varint,2,opt,name=type,proto3,enum=invite.InviteType" json:"type,omitempty"`
	ContextId     string                 `protobuf:"bytes,3,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	InviteeId     string                 `protobuf:"bytes,4,opt,name=invitee_id,json=inviteeId,proto3" json:"invitee_id,omitempty"`
	RequestorId   string                 `protobuf:"bytes,5,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	Status        InviteStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=invite.InviteStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix millis
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invite) Reset() {
	*x = Invite{}
	mi := &file_grpcapi_invite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_invite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite.ProtoReflect.Descriptor instead.
func (*Invite) Descriptor() ([]byte, []int) {
	return file_grpcapi_invite_proto_rawDescGZIP(), []int{0}
}

func (x *Invite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invite) GetType() InviteType {
	if x != nil {
		return x.Type
	}
	return InviteType_INVITE_TYPE_UNSPECIFIED
}

func (x *Invite) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Invite) GetInviteeId() string {
	if x != nil {
		return x.InviteeId
	}
	return ""
}

func (x *Invite) GetRequestorId() string {
	if x != nil {
		return x.RequestorId
	}
	return ""
}

func (x *Invite) GetStatus() InviteStatus {
	if x != nil {
		return x.Status
	}
	return InviteStatus_INVITE_STATUS_UNSPECIFIED
}

func (x *Invite) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Invite) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetUserInvitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        InviteStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=invite.InviteStatus" json:"status,omitempty"` // UNSPECIFIED = all statuses
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                            // <= 0 applies the server default
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`                           // hex id from a previous page; empty for the first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInvitesRequest) Reset() {
	*x = GetUserInvitesRequest{}
	mi := &file_grpcapi_invite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInvitesRequest) ProtoMessage() {}

func (x *GetUserInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_invite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInvitesRequest.ProtoReflect.Descriptor instead.
func (*GetUserInvitesRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_invite_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInvitesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInvitesRequest) GetStatus() InviteStatus {
	if x != nil {
		return x.Status
	}
	return InviteStatus_INVITE_STATUS_UNSPECIFIED
}

func (x *GetUserInvitesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserInvitesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetUserInvitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invites       []*Invite              `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // empty when there are no more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInvitesResponse) Reset() {
	*x = GetUserInvitesResponse{}
	mi := &file_grpcapi_invite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInvitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInvitesResponse) ProtoMessage() {}

func (x *GetUserInvitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_invite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInvitesResponse.ProtoReflect.Descriptor instead.
func (*GetUserInvitesResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_invite_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInvitesResponse) GetInvites() []*Invite {
	if x != nil {
		return x.Invites
	}
	return nil
}

func (x *GetUserInvitesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_grpcapi_invite_proto protoreflect.FileDescriptor

const file_grpcapi_invite_proto_rawDesc = "" +
	"\n" +
	"\x14grpcapi/invite.proto\x12\x06invite\"\x8d\x02\n" +
	"\x06Invite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.invite.InviteTypeR\x04type\x12\x1d\n" +
	"\n" +
	"context_id\x18\x03 \x01(\tR\tcontextId\x12\x1d\n" +
	"\n" +
	"invitee_id\x18\x04 \x01(\tR\tinviteeId\x12!\n" +
	"\frequestor_id\x18\x05 \x01(\tR\vrequestorId\x12,\n" +
	"\x06status\x18\x06 \x01(\x0e2\x14.invite.InviteStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\x8c\x01\n" +
	"\x15GetUserInvitesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.invite.InviteStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"c\n" +
	"\x16GetUserInvitesResponse\x12(\n" +
	"\ainvites\x18\x01 \x03(\v2\x0e.invite.InviteR\ainvites\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor*Q\n" +
	"\n" +
	"InviteType\x12\x1b\n" +
	"\x17INVITE_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EVENT\x10\x01\x12\b\n" +
	"\x04TEAM\x10\x02\x12\b\n" +
	"\x04CLUB\x10\x03\x12\a\n" +
	"\x03ORG\x10\x04*V\n" +
	"\fInviteStatus\x12\x1d\n" +
	"\x19INVITE_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\f\n" +
	"\bDECLINED\x10\x032`\n" +
	"\rInviteService\x12O\n" +
	"\x0eGetUserInvites\x12\x1d.invite.GetUserInvitesRequest\x1a\x1e.invite.GetUserInvitesResponseB+Z)olympsis-server/grpcapi/invitepb;invitepbb\x06proto3"

var (
	file_grpcapi_invite_proto_rawDescOnce sync.Once
	file_grpcapi_invite_proto_rawDescData []byte
)

func file_grpcapi_invite_proto_rawDescGZIP() []byte {
	file_grpcapi_invite_proto_rawDescOnce.Do(func() {
		file_grpcapi_invite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcapi_invite_proto_rawDesc), len(file_grpcapi_invite_proto_rawDesc)))
	})
	return file_grpcapi_invite_proto_rawDescData
}

var file_grpcapi_invite_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpcapi_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpcapi_invite_proto_goTypes = []any{
	(InviteType)(0),                // 0: invite.InviteType
	(InviteStatus)(0),              // 1: invite.InviteStatus
	(*Invite)(nil),                 // 2: invite.Invite
	(*GetUserInvitesRequest)(nil),  // 3: invite.GetUserInvitesRequest
	(*GetUserInvitesResponse)(nil), // 4: invite.GetUserInvitesResponse
}
var file_grpcapi_invite_proto_depIdxs = []int32{
	0, // 0: invite.Invite.type:type_name -> invite.InviteType
	1, // 1: invite.Invite.status:type_name -> invite.InviteStatus
	1, // 2: invite.GetUserInvitesRequest.status:type_name -> invite.InviteStatus
	2, // 3: invite.GetUserInvitesResponse.invites:type_name -> invite.Invite
	3, // 4: invite.InviteService.GetUserInvites:input_type -> invite.GetUserInvitesRequest
	4, // 5: invite.InviteService.GetUserInvites:output_type -> invite.GetUserInvitesResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpcapi_invite_proto_init() }
func file_grpcapi_invite_proto_init() {
	if File_grpcapi_invite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcapi_invite_proto_rawDesc), len(file_grpcapi_invite_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcapi_invite_proto_goTypes,
		DependencyIndexes: file_grpcapi_invite_proto_depIdxs,
		EnumInfos:         file_grpcapi_invite_proto_enumTypes,
		MessageInfos:      file_grpcapi_invite_proto_msgTypes,
	}.Build()
	File_grpcapi_invite_proto = out.File
	file_grpcapi_invite_proto_goTypes = nil
	file_grpcapi_invite_proto_depIdxs = nil
}
