// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: grpcapi/eventteam.proto

package eventteampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventTeamService_AddTeamMember_FullMethodName  = "/eventteam.EventTeamService/AddTeamMember"
	EventTeamService_AddParticipant_FullMethodName = "/eventteam.EventTeamService/AddParticipant"
)

// EventTeamServiceClient is the client API for EventTeamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventTeamService is the internal, inter-service write API for event teams and
// participants. It is NOT exposed through the public gateway — only other
// olympsis services call it. Its sole caller is invite-service, which invokes
// AddTeamMember when a user accepts a TEAM invite (membership = the RSVP) and
// AddParticipant when a user accepts an EVENT invite (an individual RSVP row).
type EventTeamServiceClient interface {
	AddTeamMember(ctx context.Context, in *AddTeamMemberRequest, opts ...grpc.CallOption) (*AddTeamMemberResponse, error)
	AddParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*AddParticipantResponse, error)
}

type eventTeamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventTeamServiceClient(cc grpc.ClientConnInterface) EventTeamServiceClient {
	return &eventTeamServiceClient{cc}
}

func (c *eventTeamServiceClient) AddTeamMember(ctx context.Context, in *AddTeamMemberRequest, opts ...grpc.CallOption) (*AddTeamMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTeamMemberResponse)
	err := c.cc.Invoke(ctx, EventTeamService_AddTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventTeamServiceClient) AddParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*AddParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddParticipantResponse)
	err := c.cc.Invoke(ctx, EventTeamService_AddParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventTeamServiceServer is the server API for EventTeamService service.
// All implementations must embed UnimplementedEventTeamServiceServer
// for forward compatibility.
//
// EventTeamService is the internal, inter-service write API for event teams and
// participants. It is NOT exposed through the public gateway — only other
// olympsis services call it. Its sole caller is invite-service, which invokes
// AddTeamMember when a user accepts a TEAM invite (membership = the RSVP) and
// AddParticipant when a user accepts an EVENT invite (an individual RSVP row).
type EventTeamServiceServer interface {
	AddTeamMember(context.Context, *AddTeamMemberRequest) (*AddTeamMemberResponse, error)
	AddParticipant(context.Context, *AddParticipantRequest) (*AddParticipantResponse, error)
	mustEmbedUnimplementedEventTeamServiceServer()
}

// UnimplementedEventTeamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventTeamServiceServer struct{}

func (UnimplementedEventTeamServiceServer) AddTeamMember(context.Context, *AddTeamMemberRequest) (*AddTeamMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTeamMember not implemented")
}
func (UnimplementedEventTeamServiceServer) AddParticipant(context.Context, *AddParticipantRequest) (*AddParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddParticipant not implemented")
}
func (UnimplementedEventTeamServiceServer) mustEmbedUnimplementedEventTeamServiceServer() {}
func (UnimplementedEventTeamServiceServer) testEmbeddedByValue()                          {}

// UnsafeEventTeamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventTeamServiceServer will
// result in compilation errors.
type UnsafeEventTeamServiceServer interface {
	mustEmbedUnimplementedEventTeamServiceServer()
}

func RegisterEventTeamServiceServer(s grpc.ServiceRegistrar, srv EventTeamServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventTeamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventTeamService_ServiceDesc, srv)
}

func _EventTeamService_AddTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTeamServiceServer).AddTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTeamService_AddTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTeamServiceServer).AddTeamMember(ctx, req.(*AddTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventTeamService_AddParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTeamServiceServer).AddParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTeamService_AddParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTeamServiceServer).AddParticipant(ctx, req.(*AddParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventTeamService_ServiceDesc is the grpc.ServiceDesc for EventTeamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventTeamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventteam.EventTeamService",
	HandlerType: (*EventTeamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTeamMember",
			Handler:    _EventTeamService_AddTeamMember_Handler,
		},
		{
			MethodName: "AddParticipant",
			Handler:    _EventTeamService_AddParticipant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcapi/eventteam.proto",
}
