server {
    listen 80;
    server_name api.olympsis.com;
    include /etc/nginx/conf.d/proxy_headers.conf;

    location ~ ^/v1/(auth|users|fields|venues|events|clubs|organizations|posts|reports|locales|health|map-snapshot|announcements|system) {
        proxy_pass http://127.0.0.1:8080;
        include proxy_headers.conf;
    }

    location /v1/storage {
        proxy_pass http://127.0.0.1:8081;
        include proxy_headers.conf;
        proxy_set_header X-Filename $http_x_filename;
    }

    location /v1/chats {
        proxy_pass http://127.0.0.1:8082;
        include proxy_headers.conf;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 1800;
        proxy_send_timeout 1800;
    }

    location /v1/notifications {
        proxy_pass http://127.0.0.1:8083;
        include proxy_headers.conf;
    }
}