server {
    listen 80;
    server_name api.olympsis.com;

    set $server_location http://server:80;

    location /v1/health {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/auth {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/users {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/fields {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/venues {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/events {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/clubs {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/organizations {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/posts {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/reports {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/locales {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/map-snapshot {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/announcements {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    location /v1/system {
        proxy_pass $server_location;
        include proxy_headers.conf;
    }

    # location /v1/storage {
    #     proxy_pass http://storage:8081;
    #     include proxy_headers.conf;
    #     proxy_set_header X-Filename $http_x_filename;
    # }

    # location /v1/chats {
    #     proxy_pass http://chat:8082;
    #     include proxy_headers.conf;

    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";
    #     proxy_read_timeout 1800;
    #     proxy_send_timeout 1800;
    # }

    # location /v1/notifications {
    #     proxy_pass http://notifications:8083;
    #     include proxy_headers.conf;
    # }
}