version: "3.0"

# volumes:
#     db-data:

services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d

    server:
        container_name: server
        image: us-central1-docker.pkg.dev/olympsis-408521/main/server:v0.7.0
        restart: always
        pull_policy: always
        ports:
            - 80:8080
        # volumes:
        #     - db-data:/server
        environment:
            MODE: PRODUCTION
            FIREBASE_FILE_PATH: ./files/firebase-credentials.json
            MAPKIT_TOKEN: eyJraWQiOiI3NjZXUjMyNVM4IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiI1QTZINDlRODVEIiwiaWF0IjoxNzQwMjg0NjQ1LCJleHAiOjE3NDA5MDIzOTl9.LPQlwicCot1AmWF8utQclYB2XCoN5C4oeOQyDmo-SlAGP_zWVpExAbcQGyEl6NvnWtLIM1cVLpGLcln9DxrZNw

    # storage:
    #     container_name: storage
    #     image: us-central1-docker.pkg.dev/olympsis-408521/main/storage:v1.0.0
    #     restart: always
    #     pull_policy: always
    #     ports:
    #         - 8081:7002

    # chat:
    #     container_name: chat
    #     image: us-central1-docker.pkg.dev/olympsis-408521/main/chat:v1.0.0
    #     restart: always
    #     pull_policy: always
    #     ports:
    #         - 8082:7003

    # notification:
    #     container_name: notif
    #     image: us-central1-docker.pkg.dev/olympsis-408521/main/notif:v1.0.0
    #     restart: always
    #     pull_policy: always
    #     ports:
    #         - 8083:7004