version: "3.0"
name: olympsis-dev

volumes:
    db-data:

services:
    server:
        build: ../.
        image: olympsis-server
        container_name: server
        restart: always
        ports:
            - 80:80
        volumes:
            - db-data:/server
            - ../files/firebase-credentials.json:/app/firebase-credentials.json:ro
            - ../files/localhost.key:/app/localhost.key:ro
            - ../files/localhost.crt:/app/localhost.crt:ro
        environment:
            PORT: 80
            HTTP: UNSECURE
            MODE: PRODUCTION
            KEY_FILE_PATH: ./localhost.key
            CERT_FILE_PATH: ./localhost.crt
            FIREBASE_FILE_PATH: ./firebase-credentials.json
            STRIPE_TOKEN: sk_test_51P33HvRxf68pt9NZisRo9RRtCn4OJwspd4juCFnJEip0e7oSx0WPm7Cb2M7WJ7VRs7i5LZDSs9fuyV6QahQgPuaI00oYr8nc89
            MAPKIT_TOKEN: eyJraWQiOiI3NjZXUjMyNVM4IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiI1QTZINDlRODVEIiwiaWF0IjoxNzQwMjg0NjQ1LCJleHAiOjE3NDA5MDIzOTl9.LPQlwicCot1AmWF8utQclYB2XCoN5C4oeOQyDmo-SlAGP_zWVpExAbcQGyEl6NvnWtLIM1cVLpGLcln9DxrZNw
        depends_on:
            - master-db

    # storage:
    #     container_name: storage
    #     restart: always
    #     ports:
    #         - 8081:80
    #     depends_on:
    #         - master-db

    # chat:
    #     container_name: chat
    #     restart: always
    #     ports:
    #         - 8082:80
    #     depends_on:
    #         - redis-db

    master-db:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: olympsis
        ports:
            - 27017:27017
        volumes:
            - db-data:/master
            - ./master-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    redis-db:
        container_name: redis
        image: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - db-data:/redis