version: "3.0"

name: olympsis-dev

volumes:
    db-data:

services:
    server:
        build: ../.
        image: olympsis-server
        container_name: server
        restart: always
        ports:
            - 443:443
        volumes:
            - db-data:/server
        environment:
            PORT: 443
            HTTP: SECURE
            MODE: PRODUCTION
            KEY_FILE_PATH: ./files/localhost.key
            CERT_FILE_PATH: ./files/localhost.crt
            FIREBASE_FILE_PATH: ./files/firebase-credentials.json
            MAPKIT_TOKEN: eyJraWQiOiI3NjZXUjMyNVM4IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiI1QTZINDlRODVEIiwiaWF0IjoxNzQwMjg0NjQ1LCJleHAiOjE3NDA5MDIzOTl9.LPQlwicCot1AmWF8utQclYB2XCoN5C4oeOQyDmo-SlAGP_zWVpExAbcQGyEl6NvnWtLIM1cVLpGLcln9DxrZNw
        depends_on:
            - master-db

    # storage:
    #     container_name: storage
    #     restart: always
    #     ports:
    #         - 8081:80
    #     depends_on:
    #         - master-db

    # chat:
    #     container_name: chat
    #     restart: always
    #     ports:
    #         - 8082:80
    #     depends_on:
    #         - redis-db

    # notifications:
    #     container_name: notif
    #     restart: always
    #     ports:
    #         - 8083:80
    #     depends_on:
    #         - master-db

    master-db:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: olympsis
        ports:
            - 27017:27017
        volumes:
            - db-data:/master
            - ./master-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    redis-db:
        container_name: redis
        image: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - db-data:/redis