version: "3.0"

name: olympsis-dev

volumes:
  db-data:

services:
  server:
    build: ../.
    container_name: server
    restart: always
    ports:
     - 443:443
    volumes:
      - db-data:/server
    environment:
      MODE: DEVELOPMENT
      DB_USR: admin
      DB_PASS: olympsis
      DB_ADDR: master:27017
    depends_on:
      - master-db
      

  master-db:
    container_name: master
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: olympsis
    volumes:
      - db-data:/master
      - ./master-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro