name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Image
      env:
        VERSION: 0.2.1
        SERVICE_NAME: olympsis/server
      run: | 
        docker build . -t $SERVICE_NAME:$VERSION
        docker push $SERVICE_NAME:$VERSION